version: '3.7'
services:
  mongodb:
    container_name: mongo
    image: mongo:4.4.11
    environment:
      MONGO_INITDB_ROOT_USERNAME: beny
      MONGO_INITDB_ROOT_PASSWORD: wefox
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
volumes:
  mongodb_data_container: